-- MySQL Script generated by MySQL Workbench
-- Thu Jan 13 17:27:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SA_Project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SA_Project` ;

-- -----------------------------------------------------
-- Schema SA_Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SA_Project` DEFAULT CHARACTER SET utf8 ;
USE `SA_Project` ;

-- -----------------------------------------------------
-- Table `SA_Project`.`Train`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SA_Project`.`Train` ;

CREATE TABLE IF NOT EXISTS `SA_Project`.`Train` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TrainNO` VARCHAR(64) NOT NULL,
  `TrainTypeName` VARCHAR(64) NOT NULL,
  `TrainTypePrice` INT NOT NULL,
  `StartingStation` VARCHAR(64) NOT NULL,
  `EndingStation` VARCHAR(64) NOT NULL,
  `StartingStationDepartureTime` TIME NOT NULL,
  `TrainDate` DATE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SA_Project`.`TrainDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SA_Project`.`TrainDetail` ;

CREATE TABLE IF NOT EXISTS `SA_Project`.`TrainDetail` (
  `ID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `TrainNO` VARCHAR(64) NOT NULL,
  `Direction` INT NOT NULL,
  `StopSequence` INT NOT NULL,
  `StopName` VARCHAR(64) NOT NULL,
  `StopDepartureTime` TIME NOT NULL,
  `StopArrivalTime` TIME NOT NULL,
  INDEX `TrainDetail_Train_fk_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `TrainDetail_Train_fk`
    FOREIGN KEY (`ID`)
    REFERENCES `SA_Project`.`Train` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SA_Project`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SA_Project`.`admin` ;

CREATE TABLE IF NOT EXISTS `SA_Project`.`admin` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `admin_name` VARCHAR(64) NOT NULL,
  `admin_password` VARCHAR(64) NOT NULL,
  `admin_email` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `admin_password_UNIQUE` (`admin_password` ASC) VISIBLE,
  UNIQUE INDEX `admin_email_UNIQUE` (`admin_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SA_Project`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SA_Project`.`member` ;

CREATE TABLE IF NOT EXISTS `SA_Project`.`member` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `member_name` VARCHAR(64) NOT NULL,
  `member_password` VARCHAR(64) NOT NULL,
  `member_email` VARCHAR(64) NOT NULL,
  `member_phone` VARCHAR(64) NOT NULL,
  `update_times` DATETIME NOT NULL,
  `login_times` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `member_password_UNIQUE` (`member_password` ASC) VISIBLE,
  UNIQUE INDEX `member_email_UNIQUE` (`member_email` ASC) VISIBLE,
  UNIQUE INDEX `member_phone_UNIQUE` (`member_phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SA_Project`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SA_Project`.`Book` ;

CREATE TABLE IF NOT EXISTS `SA_Project`.`Book` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `memeber_id` INT NOT NULL,
  `train_NO` INT NOT NULL,
  `departure_station` VARCHAR(64) NOT NULL,
  `arrival_station` VARCHAR(64) NOT NULL,
  `starting_station` VARCHAR(64) NOT NULL,
  `ending_station` VARCHAR(64) NOT NULL,
  `departure_time` TIME NOT NULL,
  `arrival_time` TIME NOT NULL,
  `ticket_amount` INT NOT NULL,
  `ticket_price` INT NOT NULL,
  `train_date` DATE NOT NULL,
  `train_type` VARCHAR(64) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `book_member_id_idx` (`memeber_id` ASC) VISIBLE,
  CONSTRAINT `book_member_id`
    FOREIGN KEY (`memeber_id`)
    REFERENCES `SA_Project`.`member` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SA_Project`.`member_has_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SA_Project`.`member_has_admin` ;

CREATE TABLE IF NOT EXISTS `SA_Project`.`member_has_admin` (
  `member_ID` INT NOT NULL,
  `admin_ID` INT NOT NULL,
  INDEX `fk_member_has_admin_admin1_idx` (`admin_ID` ASC) VISIBLE,
  INDEX `fk_member_has_admin_member1_idx` (`member_ID` ASC) VISIBLE,
  CONSTRAINT `fk_member_has_admin_member1`
    FOREIGN KEY (`member_ID`)
    REFERENCES `SA_Project`.`member` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_admin_admin1`
    FOREIGN KEY (`admin_ID`)
    REFERENCES `SA_Project`.`admin` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
